version: 2.1

parameters:
  node-version:
    type: string
    default: '20.10.0'

  cypress-version:
    type: string
    default: '13.6.4'

commands:
  yarn-install:
    steps:
      - run: yarn install --immutable

  install-foundry:
    steps:
      - run:
          name: Install foundry used for cannon and e2e tests
          environment:
            SHELL: /bin/bash
          command: |-
            apt update && apt install --yes curl
            curl -L https://foundry.paradigm.xyz | bash
            export PATH="$PATH:$HOME/.foundry/bin"
            echo export PATH="$PATH:$HOME/.foundry/bin" > $BASH_ENV
            foundryup

jobs:
  test:
    docker:
      - image: cypress/included:<< pipeline.parameters.cypress-version >>
    steps:
      - checkout
      - yarn-install
      - run: yarn dedupe --check
      - run: yarn pretty:check
      - run: yarn codegen && git diff --exit-code
      - run: cypress run --component --browser chrome
      - store_test_results:
          path: 'cypress/reports'
      - store_artifacts:
          path: 'cypress/screenshots'
      - store_artifacts:
          path: 'cypress/videos'

  e2e:
    parameters:
      chainId:
        type: integer
      preset:
        type: string
      rpc:
        type: string
    docker:
      - image: cypress/included:<< pipeline.parameters.cypress-version >>
    environment:
      NODE_ENV: test
      CYPRESS_SYNTHETIX_PRESET: << parameters.preset >>
    steps:
      - install-foundry

      - run:
          name: Run anvil localhost:8545
          command: anvil --fork-url << parameters.rpc >>
          background: true

      - checkout

      - yarn-install

      - run:
          name: Run server localhost:3000
          command: yarn start:ethers
          background: true

      - run:
          name: Wait for server localhost:3000
          command: wget --retry-connrefused --waitretry=20 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000

      - run:
          name: Wait for anvil localhost:8545
          command: wget -q -O - --retry-connrefused --waitretry=20 --read-timeout=20 --timeout=15 -t 10 --post-data='{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}' --header='Content-Type:application/json' http://localhost:8545

      - run: cypress run --e2e --browser chrome

      - store_test_results:
          path: 'cypress/reports'
      - store_artifacts:
          path: 'cypress/screenshots'
      - store_artifacts:
          path: 'cypress/videos'

workflows:
  version: 2.1

  tests:
    jobs:
      - test
      - e2e:
          name: 'e2e-base-mainnet'
          chainId: 8453
          preset: 'andromeda'
          rpc: 'https://mainnet.base.org'
      - e2e:
          name: 'e2e-base-sepolia'
          chainId: 84532
          preset: 'andromeda'
          rpc: 'https://sepolia.base.org'
